//! evdev 码到 keysym 名称的静态映射表。

/// 将常见 evdev 码映射为 `xmodmap -pke` 中可能出现的 keysym 名称，未知则 `evdev_<code>`。
pub fn evdev_code_to_keysym_name(code: u16) -> String {
    match lookup_keysym_name(code) {
        Some(name) => name.to_string(),
        None => format!("evdev_{code}"),
    }
}

/// 静态映射表查询：已知 evdev 码返回 keysym 名，未知返回 `None`。
fn lookup_keysym_name(code: u16) -> Option<&'static str> {
    let name = match code {
        1 => "Escape",
        2 => "1",
        3 => "2",
        4 => "3",
        5 => "4",
        6 => "5",
        7 => "6",
        8 => "7",
        9 => "8",
        10 => "9",
        11 => "0",
        12 => "minus",
        13 => "equal",
        14 => "BackSpace",
        15 => "Tab",
        16 => "q",
        17 => "w",
        18 => "e",
        19 => "r",
        20 => "t",
        21 => "y",
        22 => "u",
        23 => "i",
        24 => "o",
        25 => "p",
        26 => "bracketleft",
        27 => "bracketright",
        28 => "Return",
        29 => "Control_L",
        30 => "a",
        31 => "s",
        32 => "d",
        33 => "f",
        34 => "g",
        35 => "h",
        36 => "j",
        37 => "k",
        38 => "l",
        39 => "semicolon",
        40 => "apostrophe",
        41 => "grave",
        42 => "Shift_L",
        43 => "backslash",
        44 => "z",
        45 => "x",
        46 => "c",
        47 => "v",
        48 => "b",
        49 => "n",
        50 => "m",
        51 => "comma",
        52 => "period",
        53 => "slash",
        54 => "Shift_R",
        55 => "KP_Multiply",
        56 => "Alt_L",
        57 => "space",
        58 => "Caps_Lock",
        59 => "F1",
        60 => "F2",
        61 => "F3",
        62 => "F4",
        63 => "F5",
        64 => "F6",
        65 => "F7",
        66 => "F8",
        67 => "F9",
        68 => "F10",
        69 => "Num_Lock",
        70 => "Scroll_Lock",
        87 => "F11",
        88 => "F12",
        96 => "KP_Enter",
        97 => "Control_R",
        98 => "KP_Divide",
        99 => "Print",
        100 => "ISO_Level3_Shift",
        102 => "Home",
        103 => "Up",
        104 => "Prior",
        105 => "Left",
        106 => "Right",
        107 => "End",
        108 => "Down",
        109 => "Next",
        110 => "Insert",
        111 => "Delete",
        113 => "Mute",
        114 => "VolumeDown",
        115 => "VolumeUp",
        125 => "Super_L",
        126 => "Super_R",
        _ => return None,
    };
    Some(name)
}
